'use client';
import Link from 'next/link';import { useCms } from '@/contexts/CmsContext';import { useApp } from '@/contexts/AppContext';import { Editable } from '@/components/cms/Editable';import { Icon } from '@/components/ui/Icon';
const ascii = String.raw`   ___ __   ________  ____     ____  _______    ____  __  ______ 
  /   |\ \ / /  _/ / / / /    / __ \/ ____/ |  / / / / / / / __ )
 / /| | \ V // // / / / /    / / / / __/  | | / / / / / / / __  |
/ ___ |  | |/ // /_/ / /___ / /_/ / /___  | |/ / /_/ / /_/ / /_/ /
/_/  |_|  |_/___/\____/_____(_)____/_____/  |___/\____/_____/_____/`;
export function Hero(){const{cms,resolve}=useCms();const{lang}=useApp();return <section className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><div className="glass relative overflow-hidden rounded-[2rem] p-6 md:p-8"><div className="scan-line"/><pre className="mono mb-6 overflow-x-auto text-[8px] leading-tight text-primaryBright sm:text-xs" aria-hidden>{ascii}</pre><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-emerald/30 bg-emerald/10 px-3 py-1.5 text-sm font-bold text-emerald"><span className="h-2 w-2 animate-pulseSoft rounded-full bg-emerald"/><Editable path="dashboard.heroTag"/></div><h1 className="text-balance text-4xl font-black leading-tight tracking-[-.05em] md:text-6xl"><Editable path="dashboard.heroTitleA"/> <span className="gradient-text"><Editable path="dashboard.heroTitleB"/></span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted"><Editable path="dashboard.heroDescription"/></p><div className="mt-7 flex flex-wrap gap-3"><Link className="btn btn-primary" href="/projects"><Icon name="folder"/> {resolve(cms.dashboard.ctaPrimary)}</Link><Link className="btn btn-outline" href="/about#contact"><Icon name="send"/> {resolve(cms.dashboard.ctaSecondary)}</Link><button className="btn btn-outline" onClick={()=>print()}><Icon name="printer"/> {lang==='fa'?'چاپ CV':'Print CV'}</button></div><div className="mt-6 flex flex-wrap gap-2">{['Python','Node.js','TypeScript','Cloudflare','PostgreSQL','Redis','Docker'].map(x=><span className="tag mono" key={x}>#{x}</span>)}</div></div><aside className="glass relative overflow-hidden rounded-[2rem] p-6"><div className="absolute -end-20 -top-20 h-56 w-56 rounded-full bg-primaryBright/20 blur-3xl"/><div className="relative"><div className="mb-5 grid h-24 w-24 place-items-center rounded-3xl border border-border bg-bg2 text-3xl font-black text-primaryBright shadow-glow">AK</div><div className="space-y-4 text-sm"><Profile k={lang==='fa'?'موقعیت':'Location'} v={resolve(cms.identity.location)} icon="mapPin"/><Profile k="Email" v={cms.identity.email} icon="mail"/><Profile k={lang==='fa'?'تجربه':'Experience'} v={cms.identity.yearsExperience} icon="activity"/><Profile k={lang==='fa'?'وضعیت':'Status'} v={lang==='fa'?'آماده همکاری':'Available'} icon="zap"/></div></div></aside></section>}
function Profile({k,v,icon}:{k:string;v:string;icon:string}){return <div className="flex items-center gap-3 rounded-2xl border border-border bg-panel p-3"><Icon name={icon} className="text-primaryBright"/><div><div className="text-xs text-muted">{k}</div><div className="font-black">{v}</div></div></div>}
