'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { useApp } from '@/contexts/AppContext';
import { useCms } from '@/contexts/CmsContext';
import { navItems } from '@/lib/i18n';
import { Icon } from '@/components/ui/Icon';
import { Logo } from '@/components/ui/Logo';

export function LangThemeSwitcher(){
  const { lang, theme, setLang, setTheme } = useApp();
  const [open,setOpen]=useState(false);
  return <div className="relative"><button className="btn btn-outline h-10 px-3" onClick={()=>setOpen(o=>!o)} aria-label="language and theme"><Icon name={theme==='dark'?'moon':'sun'} size={16}/><span className="mono text-xs uppercase">{lang}/{theme}</span><Icon name="chevronDown" size={14}/></button>{open&&<div className="absolute top-12 z-50 w-56 rounded-2xl border border-border bg-surface p-2 shadow-glow ltr:left-0 rtl:right-0"><button className="flex w-full items-center justify-between rounded-xl px-3 py-2 hover:bg-white/5" onClick={()=>setLang(lang==='fa'?'en':'fa')}><span>{lang==='fa'?'English':'فارسی'}</span><Icon name="languages" size={16}/></button><button className="flex w-full items-center justify-between rounded-xl px-3 py-2 hover:bg-white/5" onClick={()=>setTheme(theme==='dark'?'light':'dark')}><span>{theme==='dark'?(lang==='fa'?'تم روز':'Light theme'):(lang==='fa'?'تم شب':'Dark theme')}</span><Icon name={theme==='dark'?'sun':'moon'} size={16}/></button></div>}</div>
}

export function TopNav(){
  const pathname = usePathname(); const { lang } = useApp(); const { cms, resolve } = useCms(); const [drawer,setDrawer]=useState(false);
  const isHome = pathname === '/';
  return <header className="no-print fixed inset-x-0 top-0 z-50 border-b border-border/70 bg-bg/70 backdrop-blur-xl"><div className="mx-auto flex h-17 max-w-[1220px] items-center justify-between gap-3 px-4 py-3"><div className="flex items-center gap-3"><button className="grid h-10 w-10 place-items-center rounded-xl border border-border bg-panel" onClick={()=>setDrawer(true)} aria-label="menu"><Icon name="menu"/></button><Link href="/"><Logo/></Link></div>{isHome&&<nav className="hidden items-center gap-1 rounded-full border border-border bg-panel p-1 lg:flex">{navItems.slice(0,7).map(n=><Link key={n.href} href={n.href} className={`rounded-full px-3 py-2 text-sm font-bold transition ${pathname===n.href?'bg-primary text-white':'text-muted hover:text-text'}`}>{resolve(n.label)}</Link>)}</nav>}<div className="flex items-center gap-2"><LangThemeSwitcher/><a href={cms.socials.find(s=>s.icon==='github')?.url || '#'} target="_blank" className="grid h-10 w-10 place-items-center rounded-xl border border-border bg-panel" aria-label="github"><Icon name="github"/></a></div></div><Drawer open={drawer} onClose={()=>setDrawer(false)} /></header>
}
function Drawer({open,onClose}:{open:boolean;onClose:()=>void}){const { lang }=useApp();const{cms,resolve}=useCms();return <div className={`fixed inset-0 z-[70] transition ${open?'':'pointer-events-none'}`}><div onClick={onClose} className={`absolute inset-0 bg-black/55 transition ${open?'opacity-100':'opacity-0'}`}/><aside className={`absolute top-0 h-full w-[min(360px,86vw)] border-border bg-surface-solid p-5 shadow-glow transition-transform duration-300 ${lang==='fa'?'right-0 border-l':'left-0 border-r'} ${open?'translate-x-0':lang==='fa'?'translate-x-full':'-translate-x-full'}`}><div className="mb-6 flex items-center justify-between"><div className="flex gap-2"><span className="mac-dot bg-rose"/><span className="mac-dot bg-amber"/><span className="mac-dot bg-emerald"/></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg border border-border"><Icon name="x" size={16}/></button></div><Logo/><nav className="mt-7 grid gap-2">{navItems.map(n=><Link onClick={onClose} key={n.href} href={n.href} className="flex items-center gap-3 rounded-xl border border-transparent px-3 py-3 text-muted hover:border-border hover:bg-panel hover:text-text"><Icon name={n.icon} size={18}/><span className="font-bold">{resolve(n.label)}</span></Link>)}</nav><div className="mt-6 rounded-2xl border border-border bg-panel p-4"><div className="mb-3 text-sm font-black">{lang==='fa'?'شبکه‌های اجتماعی':'Social links'}</div><div className="flex flex-wrap gap-2">{cms.socials.map(s=><a key={s.id} href={s.url} target="_blank" className="grid h-10 w-10 place-items-center rounded-xl border border-border bg-bg2"><Icon name={s.icon}/></a>)}</div><button onClick={()=>print()} className="btn btn-primary mt-4 w-full"><Icon name="printer"/> {lang==='fa'?'چاپ رزومه':'Print resume'}</button></div></aside></div>}
