'use client';

import { useEffect, useMemo, useState } from 'react';
import { GlassCard } from '@/components/ui/glass';
import { AppIcon, type IconName } from '@/components/ui/icons';

interface Insight { id: string; type: 'pattern' | 'suggestion' | 'achievement'; title: string; description: string; icon: IconName; }
const typeColors = { pattern: 'bg-blue-500/10 border-blue-500/20', suggestion: 'bg-yellow-500/10 border-yellow-500/20', achievement: 'bg-green-500/10 border-green-500/20' };
const authHeader = () => ({ Authorization: `Bearer ${typeof window !== 'undefined' ? localStorage.getItem('kiya_jwt') || '' : ''}` });

export default function InsightsPage() {
  const [tasks, setTasks] = useState<any[]>([]); const [health, setHealth] = useState<any[]>([]); const [habitLogs, setHabitLogs] = useState<any[]>([]);
  useEffect(()=>{ Promise.all([fetch('/api/planner/tasks',{headers:authHeader()}).then(r=>r.json()).catch(()=>null), fetch('/api/planner/health',{headers:authHeader()}).then(r=>r.json()).catch(()=>null), fetch('/api/planner/habits',{headers:authHeader()}).then(r=>r.json()).catch(()=>null)]).then(([t,h,ha])=>{if(t?.success)setTasks(t.data||[]); if(h?.success)setHealth(h.data.logs||[]); if(ha?.success)setHabitLogs(ha.data.logs||[]);}); }, []);
  const insights = useMemo<Insight[]>(()=>{ const done=tasks.filter(t=>t.status==='done'||t.status==='completed').length; const open=tasks.length-done; const energy=health.filter(h=>h.type==='energy'); const avgEnergy=energy.length?Math.round(energy.reduce((s,h)=>s+Number(h.value||0),0)/energy.length*10)/10:0; const streak=habitLogs.filter(h=>h.completed).length; const out: Insight[]=[]; if(tasks.length) out.push({id:'tasks',type:'pattern',title:'Task completion',description:`You completed ${done} of ${tasks.length} tasks. ${open ? `${open} tasks are still open.` : 'All tasks are done.'}`,icon:'target'}); if(avgEnergy) out.push({id:'energy',type:avgEnergy>=7?'achievement':'suggestion',title:'Energy pattern',description:`Your average logged energy is ${avgEnergy}/10. ${avgEnergy<7?'Try lighter planning on low-energy days.':'Great energy trend — schedule deep work there.'}`,icon:'zap'}); if(streak) out.push({id:'habit',type:'achievement',title:'Habit momentum',description:`You have ${streak} completed habit logs. Keep the chain alive.`,icon:'trophy'}); if(!out.length) out.push({id:'empty',type:'suggestion',title:'Start logging',description:'Add tasks, habits and health logs to unlock personalized insights.',icon:'idea'}); return out; },[tasks,health,habitLogs]);
  return <div className="space-y-6"><div className="flex justify-between items-center"><h1 className="text-2xl font-bold">Insights</h1><div className="text-sm text-text-3">Based on your stored data</div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{insights.map(insight=><GlassCard key={insight.id} className={typeColors[insight.type]}><div className="flex items-start gap-4"><div className="w-11 h-11 rounded-[14px] bg-white/5 flex items-center justify-center shrink-0"><AppIcon name={insight.icon} size={20}/></div><div><h3 className="font-bold mb-1">{insight.title}</h3><p className="text-text-2 text-sm">{insight.description}</p></div></div></GlassCard>)}</div></div>;
}
