import { CmsState } from './types';

const emptyText = { fa: '', en: '' };

export const defaultCmsState: CmsState = {
  version: 2,
  identity: {
    fullName: { ...emptyText },
    title: { ...emptyText },
    location: { ...emptyText },
    email: '',
    yearsExperience: 0,
    bio: { ...emptyText },
    handle: '',
  },
  brand: {
    logoLetter: '',
    logoImage: '',
    brandName: '',
    primaryColor: '#5d7ae6',
    accentColor: '#34d399',
  },
  settings: {
    defaultLanguage: 'en',
    defaultTheme: 'dark',
    githubUsername: '',
    editMode: false,
  },
  socials: [],
  dashboard: {
    heroTag: { ...emptyText },
    heroTitleA: { ...emptyText },
    heroTitleB: { ...emptyText },
    heroDescription: { ...emptyText },
    ctaPrimary: { fa: '', en: 'View projects' },
    ctaSecondary: { fa: '', en: 'Contact' },
    projects: [],
    stats: [],
  },
  about: {
    statusTitle: { ...emptyText },
    metrics: [],
    quickLinks: [],
    quote: { ...emptyText },
    welcomeTitle: { ...emptyText },
    welcomeBody: { ...emptyText },
    miniProjects: [],
    recentActivity: [],
  },
  projects: { customProjects: [] },
  resume: {
    summary: { ...emptyText },
    phone: '',
    website: '',
    experience: [],
    skills: [],
    education: [],
    languages: [],
  },
  gifts: {
    title: { ...emptyText },
    subtitle: { ...emptyText },
    donationLinks: [],
    downloadTitle: { ...emptyText },
    downloads: [],
  },
  announcements: [],
  comments: [],
  blog: { enabled: true, posts: [] },
  coupons: [],
  orders: [],
  shop: {
    title: { fa: '', en: 'Shop' },
    enabled: true,
    categories: [],
    products: [],
  },
  freelancing: {
    title: { fa: '', en: 'Services' },
    enabled: true,
    services: [],
    portfolio: [],
    pricing: [],
    contactForm: { enabled: true },
  },
  tools: {
    title: { fa: '', en: 'Tools' },
    enabled: true,
    categories: [],
    items: [],
  },
  planner: {
    enabled: true,
    plans: [],
    ai: {
      freeLayerProvider: '',
      paidLayerProvider: '',
      freeChatLimitPerDay: 10,
      systemPersona: '',
    },
    telegram: {
      botUsername: '',
      webhookEnabled: false,
      welcomeMessage: '',
    },
  },
  messages: [],
  music: {
    enabled: false,
    autoplay: false,
    loop: false,
    volume: 0.5,
    tracks: [],
  },
  heroObject: {
    kind: 'none',
    src: '',
    posterSrc: '',
    autoRotate: true,
    alt: '',
  },
  quotes: {
    enabled: false,
    kourosh: [],
    mohammadReza: [],
    rezaShah: [],
    custom: [],
  },
  seo: {
    siteName: '',
    description: '',
    keywords: '',
    ogImage: '',
  },
  analytics: { enabled: false, plausibleDomain: '', googleId: '' },
  newsletter: { enabled: false, title: { fa: '', en: 'Newsletter' }, subscribers: [] },
  leadMagnet: {
    items: [],
    exitPopupEnabled: false,
    stats: { downloads: 0, emailsCollected: 0 },
  },
  emailTemplates: {
    resendApiKeySet: false,
    items: [],
  },
};
