'use client';
import { useMemo, useRef, useState } from 'react';import { useCms } from '@/contexts/CmsContext';import { useApp } from '@/contexts/AppContext';import { Icon } from '@/components/ui/Icon';
const sections=['نمای کلی','هویت','شبکه‌های اجتماعی','صفحه اصلی','درباره من','پروژه‌ها','رزومه','هدیه‌ها','اعلان‌ها','نظرات','فروشگاه','پیام‌ها','رسانه','تنظیمات'];
export function AdminPanel(){const{cms,setCms,update,isAdmin,setIsAdmin,adminToken,setAdminToken,syncStatus,saveNow}=useCms();const{lang}=useApp();const[active,setActive]=useState(0);const[login,setLogin]=useState(adminToken);const[diag,setDiag]=useState<any>(null);async function verify(){const r=await fetch('/api/verify',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${login}`},body:JSON.stringify({token:login})}).then(r=>r.json()).catch(()=>({ok:false,error:'offline'}));setDiag(r);if(r.ok){setAdminToken(login);setIsAdmin(true)}}if(!isAdmin)return <main className="page-wrap"><div className="mx-auto max-w-lg glass rounded-os p-6"><h1 className="mb-2 text-2xl font-black">ورود ادمین</h1><p className="mb-5 text-sm text-muted">ADMIN_TOKEN را وارد کنید. Diagnostics: API / TOKEN / KV</p><input className="input mono" type="password" value={login} onChange={e=>setLogin(e.target.value)} placeholder="ADMIN_TOKEN"/><button className="btn btn-primary mt-3 w-full" onClick={verify}><Icon name="lock"/> ورود</button>{diag&&<pre className="mono mt-4 rounded-xl border border-border bg-black/30 p-3 text-xs">{JSON.stringify(diag,null,2)}</pre>}</div></main>;return <main className={`page-wrap ${cms.settings.editMode?'edit-mode':''}`}><div className="grid gap-5 lg:grid-cols-[260px_1fr]"><aside className="no-print glass rounded-os p-3"><div className="mb-3 flex items-center justify-between px-2"><b>پنل مدیریت</b><span className={`tag ${syncStatus==='synced'?'text-emerald':syncStatus==='error'?'text-rose':'text-amber'}`}>{syncStatus}</span></div>{sections.map((s,i)=><button key={s} onClick={()=>setActive(i)} className={`mb-1 flex w-full items-center gap-2 rounded-xl px-3 py-2 text-start font-bold ${active===i?'bg-primary text-white':'text-muted hover:bg-panel hover:text-text'}`}><Icon name={icon(i)} size={16}/>{s}</button>)}<button className="btn btn-outline mt-3 w-full" onClick={()=>setIsAdmin(false)}>خروج</button></aside><section className="glass rounded-os p-5"><Header title={sections[active]}/>{active===0&&<Overview/>}{active===1&&<Identity/>}{active===2&&<Socials/>}{active===3&&<Dashboard/>}{active===4&&<About/>}{active===5&&<Projects/>}{active===6&&<Resume/>}{active===7&&<Gifts/>}{active===8&&<Announcements/>}{active===9&&<Comments/>}{active===10&&<Shop/>}{active===11&&<Messages/>}{active===12&&<Media/>}{active===13&&<Settings/>}<div className="mt-6 flex gap-2"><button className="btn btn-primary" onClick={saveNow}><Icon name="save"/> ذخیره</button><button className="btn btn-outline" onClick={()=>update('settings.editMode',!cms.settings.editMode)}>Edit mode: {cms.settings.editMode?'ON':'OFF'}</button><ExportImport/></div></section></div></main>}
function Header({title}:{title:string}){return <h1 className="mb-5 border-b border-border pb-4 text-2xl font-black gradient-text">{title}</h1>}
function Field({label,path,type='text'}:{label:string;path:string;type?:string}){const{cms,update}=useCms();const v=path.split('.').reduce<any>((a,k)=>a?.[k],cms as any);return <label className="block"><span className="mb-1 block text-xs font-bold text-muted">{label}</span><input className="input" type={type} value={typeof v==='object'?JSON.stringify(v):v??''} onChange={e=>{let val:any=e.target.value;if(typeof v==='number')val=Number(val); if(typeof v==='boolean')val=e.target.checked; update(path,val)}}/></label>}
function TextField({label,path}:{label:string;path:string}){const{cms,update}=useCms();const v=path.split('.').reduce<any>((a,k)=>a?.[k],cms as any)||{fa:'',en:''};return <div className="grid gap-2 md:grid-cols-2"><label><span className="text-xs text-muted">{label} FA</span><input className="input" value={v.fa||''} onChange={e=>update(path,{...v,fa:e.target.value})}/></label><label><span className="text-xs text-muted">{label} EN</span><input className="input" value={v.en||''} onChange={e=>update(path,{...v,en:e.target.value})}/></label></div>}
function Overview(){const{cms}=useCms();return <div className="grid gap-4 md:grid-cols-4">{[['Projects',cms.dashboard.projects.length],['Comments',cms.comments.length],['Products',cms.shop.products.length],['Messages',cms.messages.length]].map(x=><div key={x[0]} className="rounded-2xl border border-border bg-panel p-5"><div className="text-3xl font-black text-primaryBright">{x[1]}</div><div className="text-sm text-muted">{x[0]}</div></div>)}</div>}
function Identity(){return <div className="grid gap-4"><TextField label="نام" path="identity.fullName"/><TextField label="عنوان" path="identity.title"/><TextField label="موقعیت" path="identity.location"/><Field label="ایمیل" path="identity.email"/><Field label="تلفن" path="identity.phone"/><Field label="وب‌سایت" path="identity.website"/><TextField label="بیو" path="identity.bio"/><ImageUpload path="brand.logoImage" label="آپلود لوگو"/></div>}
function Socials(){const{cms,update}=useCms();return <ArrayEditor path="socials" rows={cms.socials} make={()=>({id:crypto.randomUUID(),platform:'GitHub',label:'GitHub',url:'#',icon:'github'})} fields={['platform','label','url','icon']}/>}
function Dashboard(){return <div className="grid gap-4"><TextField label="Hero Tag" path="dashboard.heroTag"/><TextField label="Title A" path="dashboard.heroTitleA"/><TextField label="Title B" path="dashboard.heroTitleB"/><TextField label="Description" path="dashboard.heroDescription"/><JsonEditor path="dashboard.projects"/><JsonEditor path="dashboard.stats"/></div>}
function About(){return <div className="grid gap-4"><TextField label="Status title" path="about.statusTitle"/><TextField label="Quote" path="about.quote"/><TextField label="Welcome title" path="about.welcomeTitle"/><TextField label="Welcome body" path="about.welcomeBody"/><JsonEditor path="about.metrics"/><JsonEditor path="about.recentActivity"/></div>}
function Projects(){return <JsonEditor path="projects.customProjects"/>}
function Resume(){return <div className="grid gap-4"><TextField label="Summary" path="resume.summary"/><JsonEditor path="resume.experience"/><JsonEditor path="resume.skills"/><JsonEditor path="resume.education"/><JsonEditor path="resume.languages"/></div>}
function Gifts(){return <div className="grid gap-4"><TextField label="Title" path="gifts.title"/><TextField label="Subtitle" path="gifts.subtitle"/><JsonEditor path="gifts.downloads"/><JsonEditor path="gifts.donationLinks"/></div>}
function Announcements(){return <JsonEditor path="announcements"/>}
function Comments(){return <JsonEditor path="comments"/>}
function Shop(){return <div className="grid gap-4"><TextField label="Shop title" path="shop.title"/><JsonEditor path="shop.categories"/><JsonEditor path="shop.products"/></div>}
function Messages(){const{cms}=useCms();return <JsonEditor path="messages"/>}
function Media(){return <div className="grid gap-4"><Field label="Music src" path="music.src"/><Field label="Music title" path="music.title"/><Field label="Volume" path="music.volume"/><Field label="Hero object src" path="heroObject.src"/><Field label="Hero object poster" path="heroObject.posterSrc"/><ImageUpload path="heroObject.src" label="آپلود عکس/hero"/></div>}
function Settings(){const{cms,update,adminToken,setAdminToken}=useCms();const[newTok,setNewTok]=useState('');async function change(){if(!newTok)return;await fetch('/api/change-password',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${adminToken}`},body:JSON.stringify({newToken:newTok})});setAdminToken(newTok);alert('رمز عوض شد')}return <div className="grid gap-4"><Field label="زبان پیش‌فرض" path="settings.defaultLanguage"/><Field label="تم پیش‌فرض" path="settings.defaultTheme"/><Field label="GitHub username" path="settings.githubUsername"/><Field label="Plausible domain" path="analytics.plausibleDomain"/><Field label="Google ID" path="analytics.googleId"/><div className="rounded-2xl border border-border p-4"><b>تغییر رمز</b><input className="input mt-2" value={newTok} onChange={e=>setNewTok(e.target.value)} placeholder="ADMIN_TOKEN جدید"/><button className="btn btn-primary mt-2" onClick={change}>تغییر</button></div><pre className="mono rounded-xl border border-border bg-black/30 p-3 text-xs">Cloudflare setup: KV binding = AVIDKIYA_KV · Env secret = ADMIN_TOKEN · Build = npx @cloudflare/next-on-pages@1</pre></div>}
function JsonEditor({path}:{path:string}){const{cms,update}=useCms();const v=path.split('.').reduce<any>((a,k)=>a?.[k],cms as any);const[text,setText]=useState(JSON.stringify(v,null,2));return <label className="block"><span className="text-xs font-bold text-muted">{path}</span><textarea className="input mono min-h-60 text-xs" value={text} onChange={e=>setText(e.target.value)} onBlur={()=>{try{update(path,JSON.parse(text))}catch{alert('JSON نامعتبر')}}}/></label>}
function ArrayEditor({path,rows,fields,make}:{path:string;rows:any[];fields:string[];make:()=>any}){const{update}=useCms();function set(i:number,k:string,v:any){const n=[...rows];n[i]={...n[i],[k]:v};update(path,n)}return <div className="space-y-3">{rows.map((r,i)=><div key={r.id||i} className="rounded-xl border border-border p-3"><div className="grid gap-2 md:grid-cols-4">{fields.map(f=><input key={f} className="input" value={r[f]||''} onChange={e=>set(i,f,e.target.value)} placeholder={f}/>)}</div><button className="btn btn-outline mt-2" onClick={()=>update(path,rows.filter((_,j)=>j!==i))}>حذف</button></div>)}<button className="btn btn-primary" onClick={()=>update(path,[...rows,make()])}>افزودن</button></div>}
function ExportImport(){const{cms,setCms}=useCms();const file=useRef<HTMLInputElement>(null);return <><button className="btn btn-outline" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(cms,null,2)],{type:'application/json'}));a.download='avidkiya-cms-backup.json';a.click()}}>Export JSON</button><button className="btn btn-outline" onClick={()=>file.current?.click()}>Import JSON</button><input ref={file} className="hidden" type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(f)setCms(JSON.parse(await f.text()))}}/></>}
function ImageUpload({path,label}:{path:string;label:string}){const{update}=useCms();async function pick(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const img=new Image();const url=URL.createObjectURL(f);await new Promise(res=>{img.onload=res;img.src=url});const c=document.createElement('canvas');const max=900;const ratio=Math.min(1,max/Math.max(img.width,img.height));c.width=img.width*ratio;c.height=img.height*ratio;c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);let q=.86;let data=c.toDataURL('image/jpeg',q);while(data.length>300*1024*1.37&&q>.35){q-=.08;data=c.toDataURL('image/jpeg',q)}update(path,data)}return <label className="block"><span className="mb-1 block text-xs text-muted">{label}</span><input className="input" type="file" accept="image/*" onChange={pick}/></label>}
function icon(i:number){return ['dashboard','user','share','home','terminal','folder','fileText','gift','megaphone','messageCircle','shoppingBag','mail','music','settings'][i]||'settings'}
